### PR TITLE
Update design

### PR DESCRIPTION
**Pull request by kylebutts**
Updated design using TailwindCSS. 

Quick note: RStudio viewer does not run the javascript to use TailwindCSS, so you can only preview in a web browser. I think I might be able to fix that with my package `shiny.tailwind` but I haven't done enough research to figure out how

### CODE REVIEW

**Comment by EmilHvitfeldt** [comment]
Hello Kyle, I took a look, and the `display.js` script is disabled in your PR, is that something you could fix? The whole site hinges on that script 😅

**Comment by kylebutts** [comment]
Ahh, I didn't realize it did that when I was running it locally. I think it should work now :-)

**Comment by kylebutts** [comment]
image

**Comment by EmilHvitfeldt** [comment]
Thank you @kylebutts that looks really good! I'll merge now, and tweet about it tomorrow

**Pull request merged**
